const bcrypt = require('bcryptjs');

const initialCategories = [
  {
    name: 'Electrician',
    icon: 'Zap',
    description: 'Wiring, switchboard repair, appliance installation, and circuit troubleshooting.',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80',
    averagePrice: 500,
    isActive: true,
  },
  {
    name: 'Plumber',
    icon: 'Droplet',
    description: 'Pipe leakage, tap replacement, bathroom fitting, and drainage clearance.',
    image: 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=400&q=80',
    averagePrice: 450,
    isActive: true,
  },
  {
    name: 'Painter',
    icon: 'Paintbrush',
    description: 'Interior & exterior house painting, waterproofing, and texture designs.',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=400&q=80',
    averagePrice: 600,
    isActive: true,
  },
  {
    name: 'Carpenter',
    icon: 'Hammer',
    description: 'Furniture repair, door/window frame fitting, lock installation, and custom woodwork.',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=400&q=80',
    averagePrice: 550,
    isActive: true,
  },
  {
    name: 'Mason',
    icon: 'BrickWall',
    description: 'Brickwork, plastering, tiling, concrete repair, and renovation works.',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=400&q=80',
    averagePrice: 700,
    isActive: true,
  },
  {
    name: 'AC Repair',
    icon: 'Wind',
    description: 'AC gas refilling, filter servicing, split/window installation, and cooling repair.',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=400&q=80',
    averagePrice: 650,
    isActive: true,
  },
];

const initialUsers = [
  {
    _id: 'user_admin_01',
    name: 'Platform Administrator',
    email: 'admin@worklx.com',
    phone: '9999900000',
    password: 'Admin@123', // hashed below
    role: 'ADMIN',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    location: 'Chennai, Tamil Nadu',
    isBlocked: false,
  },
  {
    _id: 'user_seeker_01',
    name: 'Gokul M',
    email: 'gokul@gmail.com',
    phone: '9876543210',
    password: 'Seeker@123',
    role: 'SEEKER',
    profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
    location: 'Salem, Tamil Nadu',
    isBlocked: false,
  },
  {
    _id: 'user_seeker_02',
    name: 'Anita Roy',
    email: 'anita@gmail.com',
    phone: '9876543211',
    password: 'Seeker@123',
    role: 'SEEKER',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    location: 'Coimbatore, Tamil Nadu',
    isBlocked: false,
  },
  {
    _id: 'user_worker_01',
    name: 'Ravi Kumar',
    email: 'ravi@worklx.com',
    phone: '9840112233',
    password: 'Worker@123',
    role: 'WORKER',
    profileImage: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=400&q=80',
    location: 'Salem, Tamil Nadu',
    isBlocked: false,
  },
  {
    _id: 'user_worker_02',
    name: 'Suresh Patel',
    email: 'suresh@worklx.com',
    phone: '9840112234',
    password: 'Worker@123',
    role: 'WORKER',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    location: 'Salem, Tamil Nadu',
    isBlocked: false,
  },
  {
    _id: 'user_worker_03',
    name: 'Amit Sharma',
    email: 'amit@worklx.com',
    phone: '9840112235',
    password: 'Worker@123',
    role: 'WORKER',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    location: 'Coimbatore, Tamil Nadu',
    isBlocked: false,
  },
  {
    _id: 'user_worker_04',
    name: 'Rajesh Carpenter',
    email: 'rajesh@worklx.com',
    phone: '9840112236',
    password: 'Worker@123',
    role: 'WORKER',
    profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    location: 'Salem, Tamil Nadu',
    isBlocked: false,
  },
  {
    _id: 'user_worker_05',
    name: 'Mohan Mason',
    email: 'mohan@worklx.com',
    phone: '9840112237',
    password: 'Worker@123',
    role: 'WORKER',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    location: 'Erode, Tamil Nadu',
    isBlocked: false,
  },
  {
    _id: 'user_worker_06',
    name: 'Vijay Kumar',
    email: 'vijay@worklx.com',
    phone: '9840112238',
    password: 'Worker@123',
    role: 'WORKER',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    location: 'Salem, Tamil Nadu',
    isBlocked: false,
  },
];

const initialWorkerProfiles = [
  {
    _id: 'wp_01',
    userId: 'user_worker_01',
    skills: ['Electrician', 'AC Repair'],
    experience: 7,
    description: 'Master certified electrician specializing in domestic wiring, switchboard setups, inverters, and heavy load testing.',
    price: 500,
    location: 'Salem, Tamil Nadu',
    coordinates: { lat: 11.6643, lng: 78.1460 },
    availability: 'AVAILABLE',
    profileImage: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=400&q=80',
    previousWorkImages: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    rating: 4.9,
    reviewCount: 38,
  },
  {
    _id: 'wp_02',
    userId: 'user_worker_02',
    skills: ['Plumber'],
    experience: 5,
    description: 'Expert plumber for pipeline fittings, drainage clearing, modern bathroom fixtures, and leak detection.',
    price: 450,
    location: 'Salem, Tamil Nadu',
    coordinates: { lat: 11.6680, lng: 78.1520 },
    availability: 'AVAILABLE',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    previousWorkImages: [
      'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    rating: 4.8,
    reviewCount: 24,
  },
  {
    _id: 'wp_03',
    userId: 'user_worker_03',
    skills: ['Painter'],
    experience: 8,
    description: 'Specialist in Royal luxury emulsion, weathercoat exterior painting, and artistic interior textures.',
    price: 600,
    location: 'Coimbatore, Tamil Nadu',
    coordinates: { lat: 11.0168, lng: 76.9558 },
    availability: 'AVAILABLE',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    previousWorkImages: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    rating: 4.9,
    reviewCount: 42,
  },
  {
    _id: 'wp_04',
    userId: 'user_worker_04',
    skills: ['Carpenter'],
    experience: 6,
    description: 'Woodwork specialist for kitchen modular units, custom wardrobes, wooden doors, and polish works.',
    price: 550,
    location: 'Salem, Tamil Nadu',
    coordinates: { lat: 11.6500, lng: 78.1300 },
    availability: 'AVAILABLE',
    profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    previousWorkImages: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    rating: 4.7,
    reviewCount: 19,
  },
  {
    _id: 'wp_05',
    userId: 'user_worker_05',
    skills: ['Mason'],
    experience: 10,
    description: 'Experienced civil mason for wall construction, floor tiling, concrete work, and structural plastering.',
    price: 700,
    location: 'Erode, Tamil Nadu',
    coordinates: { lat: 11.3410, lng: 77.7172 },
    availability: 'AVAILABLE',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    previousWorkImages: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    rating: 4.8,
    reviewCount: 29,
  },
  {
    _id: 'wp_06',
    userId: 'user_worker_06',
    skills: ['AC Repair'],
    experience: 9,
    description: 'Certified HVAC & Inverter AC technician. Quick cooling issue resolution, gas recharging, and PCB fixing.',
    price: 650,
    location: 'Salem, Tamil Nadu',
    coordinates: { lat: 11.6690, lng: 78.1400 },
    availability: 'AVAILABLE',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    previousWorkImages: [
      'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=600&q=80',
    ],
    isVerified: true,
    rating: 5.0,
    reviewCount: 51,
  },
];

const initialBookings = [
  {
    _id: 'booking_01',
    seekerId: 'user_seeker_01',
    workerId: 'user_worker_01',
    service: 'Electrician',
    date: '2026-09-24',
    time: '10:00 AM',
    address: '14/B Fairlands Main Road, Salem, Tamil Nadu',
    description: 'Main hall ceiling fan wiring and MCB tripping issue repair.',
    serviceImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80',
    amount: 500,
    status: 'ACCEPTED',
    paymentStatus: 'PAID',
    trackingStatus: 'ON_THE_WAY',
    workerLocation: { lat: 11.6660, lng: 78.1480 },
    createdAt: new Date('2026-09-23T10:00:00Z'),
  },
  {
    _id: 'booking_02',
    seekerId: 'user_seeker_01',
    workerId: 'user_worker_02',
    service: 'Plumber',
    date: '2026-09-20',
    time: '02:30 PM',
    address: '14/B Fairlands Main Road, Salem, Tamil Nadu',
    description: 'Kitchen sink mixer tap replacement and pipe leak fixing.',
    amount: 450,
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    trackingStatus: 'SERVICE_COMPLETED',
    workerLocation: { lat: 11.6680, lng: 78.1520 },
    createdAt: new Date('2026-09-20T08:00:00Z'),
  },
  {
    _id: 'booking_03',
    seekerId: 'user_seeker_02',
    workerId: 'user_worker_03',
    service: 'Painter',
    date: '2026-09-25',
    time: '09:00 AM',
    address: '42 Gandhi Nagar, Coimbatore, Tamil Nadu',
    description: '2BHK complete interior wall painting consultation and quotation.',
    amount: 600,
    status: 'PENDING',
    paymentStatus: 'PENDING',
    trackingStatus: 'BOOKING_CREATED',
    workerLocation: { lat: 11.0168, lng: 76.9558 },
    createdAt: new Date('2026-09-23T14:30:00Z'),
  },
];

const initialReviews = [
  {
    _id: 'review_01',
    bookingId: 'booking_02',
    seekerId: 'user_seeker_01',
    workerId: 'user_worker_02',
    rating: 5,
    comment: 'Suresh arrived promptly and fixed our kitchen leak in less than 30 minutes. Extremely polite and clean work!',
    createdAt: new Date('2026-09-20T16:00:00Z'),
  },
  {
    _id: 'review_02',
    bookingId: 'booking_01',
    seekerId: 'user_seeker_02',
    workerId: 'user_worker_01',
    rating: 5,
    comment: 'Ravi is a true professional. Identified the short circuit immediately and fixed it safely. Highly recommend!',
    createdAt: new Date('2026-09-18T12:00:00Z'),
  },
];

const initialMessages = [
  {
    _id: 'msg_01',
    senderId: 'user_seeker_01',
    receiverId: 'user_worker_01',
    bookingId: 'booking_01',
    message: 'Hello Ravi, are you on your way for the wiring fix today?',
    read: true,
    createdAt: new Date('2026-09-23T09:30:00Z'),
  },
  {
    _id: 'msg_02',
    senderId: 'user_worker_01',
    receiverId: 'user_seeker_01',
    bookingId: 'booking_01',
    message: 'Yes Gokul sir! I have picked up the spare MCB switches and will reach in 10 minutes.',
    read: true,
    createdAt: new Date('2026-09-23T09:32:00Z'),
  },
];

// In-Memory Data Store (Used when MongoDB is offline / mock mode)
class MockDataStore {
  constructor() {
    this.categories = JSON.parse(JSON.stringify(initialCategories));
    this.users = JSON.parse(JSON.stringify(initialUsers)).map((u) => ({
      ...u,
      password: bcrypt.hashSync(u.password, 8),
    }));
    this.workerProfiles = JSON.parse(JSON.stringify(initialWorkerProfiles));
    this.bookings = JSON.parse(JSON.stringify(initialBookings));
    this.reviews = JSON.parse(JSON.stringify(initialReviews));
    this.messages = JSON.parse(JSON.stringify(initialMessages));
    this.payments = [];
  }
}

const mockStore = new MockDataStore();

module.exports = {
  initialCategories,
  initialUsers,
  initialWorkerProfiles,
  initialBookings,
  initialReviews,
  initialMessages,
  mockStore,
};
